defaults:
  - model: SynthRL
  - dataset: dexed
  - _self_

train:
  current_k_fold: 0
  k_folds: 5
  test_holdout_proportion: 0.2
  minibatch_size: 32
  start_epoch: 0
  end_epoch: 200
  save_period: 50
  eval_period: 10
  
loss:
  cat_softmax_t: 0.2
  label_smoothing: True

optim:
  initial_lr: 0.0002
  weight_decay: 0.0001
  adam_betas: [0.9, 0.999]

scheduler:
  warmup_epochs: 10
  warmup_start_factor: 0.2

logs_root_dir: run
run_name: stage1/seed2
verbosity: 1
main_cuda_device_idx: 0