defaults:
  - dataset: dexed
  - _self_

train:
  start_epoch: 199
  end_epoch: 400
  save_period: 50
  eval_period: 10

loss:
  param: True
  cat_softmax_t: 0.2
  label_smoothing: True
  per: True
  per_capacity: 5
  rl: True
  synth_render_workers: 16
  rl_coef: # only for stage 2
    s_value: 0.0
    e_value: 1.0
    s_epoch: 199
    e_epoch: 299

optim:
  initial_lr: 0.00002
  weight_decay: 0.0001
  betas: [0.9, 0.999]

scheduler:
  warmup_epochs: 10
  warmup_start_factor: 0.2

logs_root_dir: run
run_name: stage2/seed1
source_run_name: stage1/seed1
synth_name: dexed
verbosity: 1
main_cuda_device_idx: 0